myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='tabemory/')),
    path('admin/', admin.site.urls),
    path("tabemory/", include("tabemory.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tabemory/urls.py
from django.urls import path
from . import views




app_name = "tabemory"
urlpatterns = [
    path("create-admin/", views.create_admin_user),
    path("", views.index, name = "index"),
    path("page/create/", views.page_create, name = "page_create"),
    path("pages/", views.page_list, name = "page_list"),
    path("page/<uuid:id>/", views.page_detail, name = "page_detail"),
    path("page/<uuid:id>/update/", views.page_update, name = "page_update"),
    path("page/<uuid:id>/delete/", views.page_delete, name = "page_delete"),
]

tabemory/models.py
from django.db import models
from pathlib import Path
import uuid

class Page(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid.uuid4,editable = False,verbose_name = "ID")
    title = models.CharField(max_length = 100,verbose_name = "タイトル")
    body = models.TextField(max_length = 200,verbose_name = "本文")
    page_date = models.DateField(verbose_name = "日付")
    picture = models.ImageField(upload_to = "tabemory/picture/",blank = True, null = True, verbose_name = "写真")
    create_at = models.DateField(auto_now_add = True,verbose_name = "作成日時")
    update_at = models.DateField(auto_now = True,verbose_name = "更新日時")
    
    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        picture = self.picture
        super().delete(*args, **kwargs)
        if picture:
            Path(picture.path).unlink(missing_ok = True)

tabemory/forms.py
from django.forms import ModelForm
from .models import Page


class PageForm(ModelForm):
    class Meta:
        model = Page
        fields = ["title", "body", "page_date", "picture"]

tabemory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import PageForm
from .models import Page
from datetime import datetime
from zoneinfo import ZoneInfo
from django.contrib.auth import get_user_model

def create_admin_user(request):
    User = get_user_model()
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser("admin", "admin@example.com", "password123")
        return HttpResponse("✅ Superuser created!")
    else:
        return HttpResponse("⚠️ Admin user already exists.")

class IndexView(View):
    def get(self, request):
        datetime_now = datetime.now(
            ZoneInfo("Asia/Tokyo")
        ).strftime("%_Y年%m月%d日 %H:%M:%S")
        return render(request, "tabemory/index.html",{"datetime_now" : datetime_now})
    
    
class PageCreateView(View):
    def get(self, request):
        form = PageForm()
        return render(request, "tabemory/page_form.html", {"form" : form})
    
    def post(self, request):
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("tabemory:index")
        return render(request, "tabemory/page_form.html", {"form" : form})
    

class PageListView(View):
    def get(self,request):
        page_list = Page.objects.all()
        return render(request, "tabemory/page_list.html", {"page_list" : page_list})

class PageDetailView(View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        return render(request, "tabemory/page_detail.html", {"page" : page})
    
class PageUpdateView(View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(instance = page)
        return render(request, "tabemory/page_update.html", {"form" : form})
    
    def post(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(request.POST, request.FILES, instance = page)
        if form.is_valid():
            form.save()
            return redirect("tabemory:page_detail", id = id)
        return render(request, "tabemory/page_form.html", {"form" : form})
    
class PageDeleteView(View):
    def get(self, request, id):
        page = get_object_or_404(Page, id = id)
        return render(request, "tabemory/page_confirm_delete.html", {"page" : page})
    
    def post(self, request, id):
        page = get_object_or_404(Page, id = id)
        page.delete()
        return redirect("tabemory:page_list")
        

index = IndexView.as_view()
page_create = PageCreateView.as_view()
page_list = PageListView.as_view()
page_detail = PageDetailView.as_view()
page_update =  PageUpdateView.as_view()
page_delete = PageDeleteView.as_view()

templates/base/tabemory_base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang = "ja">
    <head>
        <meta charset="utf-8" />
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <title>たべモリー</title>
    </head>
    <body>
        <a href="{% url 'tabemory:index' %}">
            <img src="{% static 'images/logo.png' %}" alt="たべモリーロゴ" height="80" class="me-3 ms-3 mt-3 rounded" />
        </a>
        <div class = "container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

templates/tabemory/index.html
{% extends "base/tabemory_base.html" %}
{% block body %}

<p>{{ datetime_now }}</p>
<br>
<a href = "{% url 'tabemory:page_create' %}">日記を書く</a>
<br>
<a href="{% url 'tabemory:page_list' %}">ページ一覧</a>

{% endblock %}

templates/tabemory/page_confirm_delete.html
{% extends "base/tabemory_base.html" %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <p>削除しますか？</p>
    <button type="submit">削除</button>
</form>
<h2>{{ page.title }}</h2>
<div>{{ page.page_date }}</div>
<div>{{ page.body | linebreaksbr }}</div>
{% if page.picture %}
    <img src="{{ page.picture.url }}"/>
{% endif %}
<br>

{% endblock %}

templates/tabemory/page_detail.html
{% extends "base/tabemory_base.html" %}
{% block body %}

<h2>{{ page.title }}</h2>
<div>{{ page.page_date }}</div>
<div>{{ page.body | linebreaksbr }}</div>
{% if page.picture %}
    <img src="{{ page.picture.url }}"/>
{% endif %}
<br>
<a href="{% url 'tabemory:page_update' page.id %}">編集</a>
<a href="{% url 'tabemory:page_delete' page.id %}">削除</a>

{% endblock %}

templates/tabemory/page_form.html
{% extends "base/tabemory_base.html" %}
{% block body %}

<h2>日記を書く</h2>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">保存</button>
</form>

{% endblock %}

templates/tabemory/page_list.html
{% extends "base/tabemory_base.html" %}
{% block body %}

<ul>
    {% for page in page_list %}
        <li>{{ page.page_date }}: <a href="{% url 'tabemory:page_detail' page.id %}">{{ page.title }}</a></li>
    {% empty %}
        <div>日記のページが１つもありません。</div>
    {% endfor %}
</ul>

{% endblock %}

templates/tabemory/page_update.html
{% extends "base/tabemory_base.html" %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">更新</button>
</form>

{% endblock %}